repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: venv/bin/python3 -m black
        args: [--config=pyproject.toml]
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: venv/bin/python3 -m flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: venv/bin/python3 -m mypy
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: venv/bin/python3 -m isort
        types: [python]
        args: ["--profile", "black"]