"""create board, card and comment tables

Revision ID: 32467300e0e8
Revises: 9925c79b6be2
Create Date: 2022-09-25 12:55:38.096925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.base import DateTime

# revision identifiers, used by Alembic.
revision = '32467300e0e8'
down_revision = '9925c79b6be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', DateTime(), nullable=True),
    sa.Column('date_modified', DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='boardstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', DateTime(), nullable=True),
    sa.Column('date_modified', DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('owner', 'member', name='userroletype'), nullable=False),
    sa.Column('status', sa.Enum('approved', 'waiting', 'decline', name='state'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', DateTime(), nullable=True),
    sa.Column('date_modified', DateTime(), nullable=True),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('estimated_start', sa.DateTime(), nullable=True),
    sa.Column('estimated_finish', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('todo', 'in_progress', 'in_review', 'done', name='cardstate'), nullable=False),
    sa.Column('status', sa.Enum('active', 'passive', 'deleted', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', DateTime(), nullable=True),
    sa.Column('date_modified', DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('comment')
    op.drop_table('card')
    op.drop_table('board_user')
    op.drop_table('board')
    # ### end Alembic commands ###
